# -*- coding: utf-8 -*-
"""variables

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mHJNQWmWEOn0hmqWxdh15ox-9Dxu3vt3

# Variables
"""

name = 'Berru'
name

age = 22
age

print(name)
print(age)

print(type(name))
print(type(age))

name = 'Berru'
type(name)

items = ['Apple', 1.49, 'Banana', 2.56, 'Berry', 3.45, 'Cherry', 2.03]
print(items, type(items))

print(items[6])

print(items[1:5])

print(items[3:])

print(items[:3])

items[2] = 'Melon'
print(items)

age = 22
print(age, type(age))

age = 22
age += 0.5
print(age, type(age))

age = '22'
print(type(age))

age = int(age)
print(age, type(age))